palette_index:
    path:     /
    defaults: { _controller: "PaletteBundle:Palette:index" }
    methods:  GET

palette_show:
    path:     /{numLot}/show
    defaults: { _controller: "PaletteBundle:Palette:show" }
    methods:  GET

palette_new:
    path:     /new
    defaults: { _controller: "PaletteBundle:Palette:new" }
    methods:  [GET, POST]

palette_edit:
    path:     /{numLot}/edit
    defaults: { _controller: "PaletteBundle:Palette:edit" }
    methods:  [GET, POST]

palette_delete:
    path:     /delete
    defaults: { _controller: "PaletteBundle:Palette:delete" }

